/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Car_Rental;

/**
 *
 * @author User
 */
import javax.swing.JOptionPane;
import java.io.IOException;
import java.io.FileReader;
import java.io.BufferedReader;

import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

import java.io.FileWriter;

public class MagCar extends javax.swing.JFrame {
    
    /**
     * Creates new form MagCar
     */
    public MagCar() {
        initComponents();
        inition();
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        editButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        savaButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        CarModel = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        CarType = new javax.swing.JComboBox<>();
        NumSeats = new javax.swing.JComboBox<>();
        CarColor = new javax.swing.JComboBox<>();
        Auto = new javax.swing.JRadioButton();
        Mannual = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        Price = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        AirconFeature1 = new javax.swing.JCheckBox();
        gpsFeature2 = new javax.swing.JCheckBox();
        bluetoothFeature3 = new javax.swing.JCheckBox();
        airbagFeature4 = new javax.swing.JCheckBox();
        sunroofFeature5 = new javax.swing.JCheckBox();
        search = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        jLabel1.setText("Manage Car");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(17, 17, 17))
        );

        editButton.setText("Edit");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        savaButton.setText("Save (After Edit)");
        savaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savaButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Car Model: ");

        CarModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarModelActionPerformed(evt);
            }
        });

        jLabel3.setText("Car Type:");

        jLabel4.setText("Number of Seats:");

        jLabel5.setText("Car Color: ");

        jLabel6.setText("Gearbox: ");

        CarType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sedans", "SUVs", "Trucks", "Hatchbacks", "Coupes", "Vans/Minivans", "Compact Cars", "Luxury Cars" }));

        NumSeats.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15" }));
        NumSeats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumSeatsActionPerformed(evt);
            }
        });

        CarColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Black", "White", "Gray", "Red", "Yellow", "Green", "Blue" }));

        Auto.setText("Automatic");

        Mannual.setText("Mannual");
        Mannual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MannualActionPerformed(evt);
            }
        });

        jLabel7.setText("Price /day:");

        Price.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "75", "100", "150", "200", "250", "300", "350", "400", "450", "500" }));

        jLabel8.setText("Features:");

        AirconFeature1.setText("Air conditioning");
        AirconFeature1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AirconFeature1ActionPerformed(evt);
            }
        });

        gpsFeature2.setText("GPS");

        bluetoothFeature3.setText("Bluetooth");
        bluetoothFeature3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bluetoothFeature3ActionPerformed(evt);
            }
        });

        airbagFeature4.setText("Air bags");
        airbagFeature4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                airbagFeature4ActionPerformed(evt);
            }
        });

        sunroofFeature5.setText("Sunroof");

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CarModel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CarType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Auto)
                                    .addComponent(CarColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NumSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Mannual))))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AirconFeature1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(Price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8)
                            .addComponent(gpsFeature2)
                            .addComponent(bluetoothFeature3)
                            .addComponent(airbagFeature4)
                            .addComponent(sunroofFeature5))))
                .addContainerGap(115, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(editButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(savaButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteButton)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchButton)
                    .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CarModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(Price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(CarType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(NumSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AirconFeature1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(CarColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gpsFeature2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Auto)
                    .addComponent(bluetoothFeature3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Mannual)
                    .addComponent(airbagFeature4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sunroofFeature5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editButton)
                    .addComponent(deleteButton)
                    .addComponent(savaButton)
                    .addComponent(backButton))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inition() {
    // Other initialization code
    
    // Initially disable editing components
    disableEditingComponents();
    // Initially disable buttons
    disableButtons();
    
    // Add action listener to the Edit button
    editButton.addActionListener(new ActionListener() {
        public void actionPerformed(ActionEvent evt) {
            enableEditingComponents(); // Enable editing components when Edit button is clicked
            savaButton.setEnabled(true);
            deleteButton.setEnabled(true);
        }
    });

    // Add action listener to the Save (After Edit) button
    savaButton.addActionListener(new ActionListener() {
        public void actionPerformed(ActionEvent evt) {
            // Check if all required fields are filled
            if (areAllFieldsFilled()) {
                // Save changes and disable editing components
                saveChanges();
                disableEditingComponents();
                deleteButton.setEnabled(false);
                savaButton.setEnabled(false);
            } else {
                // Enable editing components if not all fields are filled
                enableEditingComponents();
                JOptionPane.showMessageDialog(Mag_Car.this, "Please fill in all required fields!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    });
    
    // Add action listener to the Automatic radio button
    Auto.addActionListener(new ActionListener() {
        public void actionPerformed(ActionEvent evt) {
            // Deselect the Manual radio button
            Mannual.setSelected(false);
        }
    });

    // Add action listener to the Manual radio button
    Mannual.addActionListener(new ActionListener() {
        public void actionPerformed(ActionEvent evt) {
            // Deselect the Automatic radio button
            Auto.setSelected(false);
        }
    });
}
    
// Method to check if all required fields are filled
private boolean areAllFieldsFilled() {
    return !CarModel.getText().isEmpty() &&
           NumSeats.getSelectedItem() != null &&
           CarColor.getSelectedItem() != null &&
           Price.getSelectedItem() != null &&
           (Auto.isSelected() || Mannual.isSelected()); // Check gearbox selection
}

    
private void disableButtons() {
    editButton.setEnabled(false);
    savaButton.setEnabled(false);
    deleteButton.setEnabled(false);
}

// Method to disable editing components
private void disableEditingComponents() {
    CarModel.setEditable(false);
    CarType.setEnabled(false);
    NumSeats.setEnabled(false);
    CarColor.setEnabled(false);
    Auto.setEnabled(false);
    Mannual.setEnabled(false);
    Price.setEnabled(false);
    AirconFeature1.setEnabled(false);
    gpsFeature2.setEnabled(false);
    bluetoothFeature3.setEnabled(false);
    airbagFeature4.setEnabled(false);
    sunroofFeature5.setEnabled(false);
}

// Method to enable editing components
private void enableEditingComponents() {
    CarModel.setEditable(true);
    CarType.setEnabled(true);
    NumSeats.setEnabled(true);
    CarColor.setEnabled(true);
    Auto.setEnabled(true);
    Mannual.setEnabled(true);
    Price.setEnabled(true);
    AirconFeature1.setEnabled(true);
    gpsFeature2.setEnabled(true);
    bluetoothFeature3.setEnabled(true);
    airbagFeature4.setEnabled(true);
    sunroofFeature5.setEnabled(true);
}

private void saveChanges() {    
    // Get the car ID entered by the user for searching
    String carIdToSearch = search.getText().trim();
    
    // Define a StringBuilder to store the modified lines
    StringBuilder modifiedContent = new StringBuilder();
    
    // Define a boolean flag to track if the car ID is found
    boolean found = false;

    // Define a FileReader and BufferedReader to read from the file
    try (FileReader fileReader = new FileReader("car_info.txt");
         BufferedReader bufferedReader = new BufferedReader(fileReader)) {
        
        String line;
        String carId = null; // Variable to store the current car ID being processed
        
        // Loop through each line in the file
        while ((line = bufferedReader.readLine()) != null) {
            // Split the line by ":"
            String[] parts = line.split(":");
            
            // Check if the first part of the line is "Car ID"
            if (parts.length > 1 && parts[0].trim().equals("Car ID")) {
                // If the car ID matches, set found to true and store the current car ID
                if (parts[1].trim().equals(carIdToSearch)) {
                    found = true;
                    carId = carIdToSearch;
                    modifiedContent.append(line).append("\n"); // Append the found car ID line
                } else {
                    carId = null;
                }
            }
            
            // If the car ID matches the searched ID, modify the information
            if (carId != null) {
                // Append the modified content
                if (parts.length > 1 && !parts[0].trim().equals("Car ID")) {
                    switch (parts[0].trim()) {
                        case "Car Model":
                            modifiedContent.append("Car Model: ").append(CarModel.getText()).append("\n");
                            break;
                        case "Car Type":
                            modifiedContent.append("Car Type: ").append(CarType.getSelectedItem()).append("\n");
                            break;
                        case "Number of Seats":
                            modifiedContent.append("Number of Seats: ").append(NumSeats.getSelectedItem()).append("\n");
                            break;
                        case "Car Color":
                            modifiedContent.append("Car Color: ").append(CarColor.getSelectedItem()).append("\n");
                            break;
                        case "Gearbox":
                            modifiedContent.append("Gearbox: ").append(Auto.isSelected() ? "Automatic" : "Manual").append("\n");
                            break;
                        case "Price /day":
                            modifiedContent.append("Price /day: ").append(Price.getSelectedItem()).append("\n");
                            break;
                        case "Features":
                            StringBuilder features = new StringBuilder();
                            if (AirconFeature1.isSelected()) features.append("Air conditioning, ");
                            if (gpsFeature2.isSelected()) features.append("GPS, ");
                            if (bluetoothFeature3.isSelected()) features.append("Bluetooth, ");
                            if (airbagFeature4.isSelected()) features.append("Air Bags, ");
                            if (sunroofFeature5.isSelected()) features.append("Sunroof, ");
                            if (features.length() > 0) features.setLength(features.length() - 2);
                            modifiedContent.append("Features: ").append(features).append("\n\n");
                            break;
                        default:
                            modifiedContent.append(line).append("\n");
                            break;
                    }
                }
            } else {
                // If the line doesn't contain the searched ID, append it as it is
                modifiedContent.append(line).append("\n");
            }
        }
    } catch (IOException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error reading file!", "Error", JOptionPane.ERROR_MESSAGE);
        return; // Exit the method if an error occurs
    }
    
    // If car ID not found, display an error message
    if (!found) {
        JOptionPane.showMessageDialog(this, "Car ID not found!", "Error", JOptionPane.ERROR_MESSAGE);
        return; // Exit the method if car ID is not found
    }
    
    // Write the modified content back to the file
    try (FileWriter fileWriter = new FileWriter("car_info.txt")) {
        fileWriter.write(modifiedContent.toString());
        JOptionPane.showMessageDialog(this, "Car information updated successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
    } catch (IOException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error writing to file!", "Error", JOptionPane.ERROR_MESSAGE);
    }
}





    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // Read the car ID entered in the search field
    String carIdToSearch = search.getText().trim();
    
    // Define a FileReader and BufferedReader to read from the file
    try (FileReader fileReader = new FileReader("car_info.txt");
         BufferedReader bufferedReader = new BufferedReader(fileReader)) {
        
        String line;
        boolean found = false;
        
        // Loop through each line in the file
        while ((line = bufferedReader.readLine()) != null) {
            // Split the line by ":"
            String[] parts = line.split(":");
            
            // Check if the first part of the line is "Car ID"
            if (parts.length > 1 && parts[0].trim().equals("Car ID")) {
                // If the car ID matches, display the information in the text fields
                if (parts[1].trim().equals(carIdToSearch)) {
                    CarModel.setText(bufferedReader.readLine().split(":")[1].trim());
                    CarType.setSelectedItem(bufferedReader.readLine().split(":")[1].trim());
                    NumSeats.setSelectedItem(bufferedReader.readLine().split(":")[1].trim());
                    CarColor.setSelectedItem(bufferedReader.readLine().split(":")[1].trim());
                    // Read the gearbox line and set radio buttons accordingly
                    String gearbox = bufferedReader.readLine().split(":")[1].trim();
                    if (gearbox.equals("Automatic")) {
                        Auto.setSelected(true);
                        Mannual.setSelected(false); // Ensure only one radio button is selected
                    } else if (gearbox.equals("Manual")) {
                        Mannual.setSelected(true);
                        Auto.setSelected(false); // Ensure only one radio button is selected
                    }
                    Price.setSelectedItem(bufferedReader.readLine().split(":")[1].trim());
                    // Read the features line and set checkboxes accordingly
                    String features = bufferedReader.readLine().split(":")[1].trim();
                    AirconFeature1.setSelected(features.contains("Air conditioning"));
                    gpsFeature2.setSelected(features.contains("GPS"));
                    bluetoothFeature3.setSelected(features.contains("Bluetooth"));
                    airbagFeature4.setSelected(features.contains("Air Bags"));
                    sunroofFeature5.setSelected(features.contains("Sunroof"));
                    
                    // Set found flag to true
                    found = true;
                    break; // Exit the loop once found
                }
            }
        }
        
        // If car ID not found, display an error message
        if (!found) {
            JOptionPane.showMessageDialog(this, "Car ID not found!", "Error", JOptionPane.ERROR_MESSAGE);
                savaButton.setEnabled(false);
                deleteButton.setEnabled(false);
                editButton.setEnabled(false);
        } else {
            // If car ID found, enable the Save and Delete buttons
            editButton.setEnabled(true);
        }
    } catch (IOException ex) {
        // Handle IOException
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error reading file!", "Error", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_searchButtonActionPerformed

    private void CarModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarModelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CarModelActionPerformed

    private void NumSeatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumSeatsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumSeatsActionPerformed

    private void MannualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MannualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MannualActionPerformed

    private void AirconFeature1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AirconFeature1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AirconFeature1ActionPerformed

    private void bluetoothFeature3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bluetoothFeature3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bluetoothFeature3ActionPerformed

    private void airbagFeature4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_airbagFeature4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_airbagFeature4ActionPerformed

    private void savaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_savaButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
            backButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                // Create an instance of the AdminMenu frame
                AdminMenu AdmenuFrame = new AdminMenu();
                // Set the frame visible
                AdmenuFrame.setVisible(true);
                // Close the current frame (AdminMenu frame)
                dispose();
            }
        });    
    }//GEN-LAST:event_backButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // Read the car ID entered in the search field
    String carIdToDelete = search.getText().trim();

    // Display a confirmation dialog before deleting
    int dialogResult = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete the record with Car ID: " + carIdToDelete + "?", "Confirm Deletion", JOptionPane.YES_NO_OPTION);
    if (dialogResult != JOptionPane.YES_OPTION) {
        return; // Exit the method if user cancels the deletion
    }

    // Define a StringBuilder to store the remaining content
    StringBuilder remainingContent = new StringBuilder();

    // Define a boolean flag to track if the car ID is found
    boolean found = false;

    // Define a FileReader and BufferedReader to read from the file
    try (FileReader fileReader = new FileReader("car_info.txt");
         BufferedReader bufferedReader = new BufferedReader(fileReader)) {

        String line;
        boolean isDeleting = false;

        // Loop through each line in the file
        while ((line = bufferedReader.readLine()) != null) {
            // Split the line by ":"
            String[] parts = line.split(":");

            // Check if the first part of the line is "Car ID"
            if (parts.length > 1 && parts[0].trim().equals("Car ID")) {
                // If the car ID matches, set found flag to true
                if (parts[1].trim().equals(carIdToDelete)) {
                    found = true;
                    isDeleting = true; // Start deleting from this line
                } else {
                    isDeleting = false; // Stop deleting if next car ID is reached
                }
            }

            // If not deleting, append the line to the remaining content
            if (!isDeleting) {
                remainingContent.append(line).append("\n");
            }
        }
    } catch (IOException ex) {
        // Handle IOException
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error reading file!", "Error", JOptionPane.ERROR_MESSAGE);
        return; // Exit the method if an error occurs
    }

    // If car ID not found, display an error message
    if (!found) {
        JOptionPane.showMessageDialog(this, "Car ID not found!", "Error", JOptionPane.ERROR_MESSAGE);
        return; // Exit the method if car ID is not found
    }

    // Write the remaining content back to the file
    try (FileWriter fileWriter = new FileWriter("car_info.txt")) {
        fileWriter.write(remainingContent.toString());
        JOptionPane.showMessageDialog(this, "Car information deleted successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
        // Clear search field and disable buttons after successful deletion
        search.setText("");
        disableButtons();
    } catch (IOException ex) {
        // Handle IOException
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error writing to file!", "Error", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_deleteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MagCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MagCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MagCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MagCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MagCar().setVisible(true);
            }
        });
    }
    
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox AirconFeature1;
    private javax.swing.JRadioButton Auto;
    private javax.swing.JComboBox<String> CarColor;
    private javax.swing.JTextField CarModel;
    private javax.swing.JComboBox<String> CarType;
    private javax.swing.JRadioButton Mannual;
    private javax.swing.JComboBox<String> NumSeats;
    private javax.swing.JComboBox<String> Price;
    private javax.swing.JCheckBox airbagFeature4;
    private javax.swing.JButton backButton;
    private javax.swing.JCheckBox bluetoothFeature3;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JCheckBox gpsFeature2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton savaButton;
    private javax.swing.JTextField search;
    private javax.swing.JButton searchButton;
    private javax.swing.JCheckBox sunroofFeature5;
    // End of variables declaration//GEN-END:variables
}
